-- MySQL Script generated by MySQL Workbench
-- mar 04 abr 2017 16:26:23 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, 

FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, 

SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinica_veterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_veterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_veterinaria` DEFAULT 

CHARACTER SET utf8 ;
USE `clinica_veterinaria` ;

-- -----------------------------------------------------
-- Table `clinica_veterinaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_veterinaria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_veterinaria`.`tipo_raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_veterinaria`.`tipo_raza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('mezclada', 'pura') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_veterinaria`.`tipo_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_veterinaria`.`tipo_animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('perro', 'gato') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_veterinaria`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_veterinaria`.`mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cliente` INT NOT NULL,
  `tipo_raza` INT NOT NULL,
  `tipo_animal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mascota_usuario_idx` (`cliente` ASC),
  INDEX `fk_mascota_tipo_raza1_idx` (`tipo_raza` ASC),
  INDEX `fk_mascota_tipo_animal1_idx` (`tipo_animal` ASC),
  CONSTRAINT `fk_mascota_usuario`
    FOREIGN KEY (`cliente`)
    REFERENCES `clinica_veterinaria`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_tipo_raza1`
    FOREIGN KEY (`tipo_raza`)
    REFERENCES `clinica_veterinaria`.`tipo_raza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_tipo_animal1`
    FOREIGN KEY (`tipo_animal`)
    REFERENCES `clinica_veterinaria`.`tipo_animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `tipo_animal` (`id`, `nombre`) VALUES (NULL, 

'perro'), (NULL, 'gato');

INSERT INTO `tipo_raza` (`id`, `nombre`) VALUES (NULL, 

'mezclada'), (NULL, 'pura');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;